name: rsa_pkcs
version: 1.1.3
description: Privacy-Enhanced Mail (PEM) parser, RSA, PKCS#1, PKCS#8, X.509
homepage: https://github.com/amaurel/rsa_pkcs
repository: https://github.com/amaurel/rsa_pkcs

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  asn1lib: "^0.6.4"

dev_dependencies:
  test: "^1.0.0"
